// Fishing Island Game Data: Fish, Rods, Baits, Trees & Rarities
// Featuring Normal, Monster, and Colossal Titan Fish!

window.GAME_DATA = {
  // RARITY DEFINITIONS
  rarities: {
    common: { name: 'Common', color: '#95a5a6', glow: '#bdc3c7', rateMult: 1.0 },
    uncommon: { name: 'Uncommon', color: '#2ecc71', glow: '#58d68d', rateMult: 0.6 },
    rare: { name: 'Rare', color: '#3498db', glow: '#5dade2', rateMult: 0.3 },
    epic: { name: 'Epic', color: '#9b59b6', glow: '#bb8fce', rateMult: 0.12 },
    legendary: { name: 'Legendary', color: '#f39c12', glow: '#f7dc6f', rateMult: 0.04 },
    colossal: { name: 'Colossal Titan', color: '#ff3838', glow: '#ff4d4d', rateMult: 0.015 }
  },

  // 36 DIVERSE FISH SPECIES (INCLUDING GIGANTIC & COLOSSAL MONSTERS)
  fish: [
    // --- COMMON FISH ---
    {
      id: 'sardine',
      name: 'Silver Sardine',
      scientific: 'Sardina pilchardus',
      rarity: 'common',
      sizeCategory: 'Small',
      habitat: 'ocean_shore',
      timeOfDay: 'all',
      preferredBait: ['worm', 'dough'],
      minSize: 12,
      maxSize: 25,
      basePrice: 15,
      fight: { stamina: 10, speed: 0.8, erraticness: 0.2, type: 'cruiser' },
      modelType: 'slender',
      colors: { body: 0xa4b0be, fin: 0xced6e0, belly: 0xf1f2f6 },
      desc: 'A shimmering small ocean swimmer that moves in vast glittering schools along the sunny shallows.'
    },
    {
      id: 'bluegill',
      name: 'Pond Bluegill',
      scientific: 'Lepomis macrochirus',
      rarity: 'common',
      sizeCategory: 'Small',
      habitat: 'freshwater_pond',
      timeOfDay: 'all',
      preferredBait: ['worm', 'cricket', 'dough'],
      minSize: 14,
      maxSize: 28,
      basePrice: 18,
      fight: { stamina: 12, speed: 0.9, erraticness: 0.3, type: 'cruiser' },
      modelType: 'panfish',
      colors: { body: 0x3d3d3d, fin: 0x2e86de, belly: 0xff9f43 },
      desc: 'A frisky disc-shaped fish with a distinctive blue ear flap. Loves hanging out under willow branches.'
    },
    {
      id: 'common_carp',
      name: 'Bronze Mirror Carp',
      scientific: 'Cyprinus carpio',
      rarity: 'common',
      sizeCategory: 'Medium',
      habitat: 'freshwater_pond',
      timeOfDay: 'all',
      preferredBait: ['dough', 'worm'],
      minSize: 45,
      maxSize: 95,
      basePrice: 32,
      fight: { stamina: 20, speed: 0.7, erraticness: 0.2, type: 'sinker' },
      modelType: 'carp',
      colors: { body: 0xb7950b, fin: 0x9a7d0a, belly: 0xf9e79f },
      desc: 'A hefty bottom-dweller with golden-bronze mirror scales and whisker-like barbels that forage near the pond mud.'
    },
    {
      id: 'clownfish',
      name: 'Anemone Clownfish',
      scientific: 'Amphiprion ocellaris',
      rarity: 'common',
      sizeCategory: 'Small',
      habitat: 'ocean_shore',
      timeOfDay: 'day',
      preferredBait: ['shrimp', 'worm'],
      minSize: 8,
      maxSize: 17,
      basePrice: 30,
      fight: { stamina: 11, speed: 1.1, erraticness: 0.4, type: 'dart' },
      modelType: 'panfish',
      colors: { body: 0xff6348, fin: 0xee5253, belly: 0xffffff, stripes: true },
      desc: 'Vibrant orange fish with bold white vertical bands. Often seen playing around coastal reef corals.'
    },
    {
      id: 'mackerel',
      name: 'Tiger Mackerel',
      scientific: 'Scomber scombrus',
      rarity: 'common',
      sizeCategory: 'Medium',
      habitat: 'ocean_deep',
      timeOfDay: 'all',
      preferredBait: ['anchovy', 'worm'],
      minSize: 28,
      maxSize: 55,
      basePrice: 38,
      fight: { stamina: 18, speed: 1.3, erraticness: 0.3, type: 'cruiser' },
      modelType: 'torpedo',
      colors: { body: 0x10ac84, fin: 0x1dd1a1, belly: 0xc8d6e5 },
      desc: 'A torpedo-shaped speedster with vivid green-blue iridescent zebra waves along its spine.'
    },
    {
      id: 'tilapia',
      name: 'Island River Tilapia',
      scientific: 'Oreochromis niloticus',
      rarity: 'common',
      sizeCategory: 'Medium',
      habitat: 'freshwater_pond',
      timeOfDay: 'day',
      preferredBait: ['dough', 'grub'],
      minSize: 25,
      maxSize: 48,
      basePrice: 28,
      fight: { stamina: 16, speed: 0.85, erraticness: 0.25, type: 'cruiser' },
      modelType: 'panfish',
      colors: { body: 0x57606f, fin: 0x747d8c, belly: 0xf1f2f6 },
      desc: 'A hardy and peaceful freshwater herbivore fond of sunny warm pond shallows.'
    },

    // --- UNCOMMON FISH ---
    {
      id: 'rainbow_trout',
      name: 'Steelhead Rainbow Trout',
      scientific: 'Oncorhynchus mykiss',
      rarity: 'uncommon',
      sizeCategory: 'Medium',
      habitat: 'freshwater_pond',
      timeOfDay: 'all',
      preferredBait: ['cricket', 'grub', 'lure'],
      minSize: 40,
      maxSize: 85,
      basePrice: 75,
      fight: { stamina: 25, speed: 1.45, erraticness: 0.5, type: 'dart' },
      modelType: 'torpedo',
      colors: { body: 0x2ed573, fin: 0xff4757, belly: 0xffa801, rainbowLine: true },
      desc: 'A jewel of cold spring waters, boasting iridescent pink and emerald hues. Leaps acrobatically when hooked!'
    },
    {
      id: 'red_snapper',
      name: 'Crimson Reef Snapper',
      scientific: 'Lutjanus campechanus',
      rarity: 'uncommon',
      sizeCategory: 'Medium',
      habitat: 'ocean_shore',
      timeOfDay: 'all',
      preferredBait: ['anchovy', 'squid', 'worm'],
      minSize: 45,
      maxSize: 95,
      basePrice: 85,
      fight: { stamina: 28, speed: 1.25, erraticness: 0.4, type: 'sinker' },
      modelType: 'snapper',
      colors: { body: 0xff3838, fin: 0xc0392b, belly: 0xffcccc },
      desc: 'A prized saltwater game fish displaying vivid crimson scales and a formidable fighting spirit.'
    },
    {
      id: 'largemouth_bass',
      name: 'Trophy Largemouth Bass',
      scientific: 'Micropterus salmoides',
      rarity: 'uncommon',
      sizeCategory: 'Medium',
      habitat: 'freshwater_pond',
      timeOfDay: 'day',
      preferredBait: ['cricket', 'grub', 'lure'],
      minSize: 38,
      maxSize: 78,
      basePrice: 80,
      fight: { stamina: 28, speed: 1.35, erraticness: 0.6, type: 'floater' },
      modelType: 'bass',
      colors: { body: 0x1e824c, fin: 0x166534, belly: 0xdcfce7 },
      desc: 'An aggressive freshwater predator that lurks near sunken logs and explodes with power on the strike.'
    },
    {
      id: 'sea_bass',
      name: 'Black Sea Bass',
      scientific: 'Centropristis striata',
      rarity: 'uncommon',
      sizeCategory: 'Medium',
      habitat: 'ocean_deep',
      timeOfDay: 'all',
      preferredBait: ['squid', 'anchovy'],
      minSize: 42,
      maxSize: 80,
      basePrice: 90,
      fight: { stamina: 30, speed: 1.15, erraticness: 0.4, type: 'sinker' },
      modelType: 'bass',
      colors: { body: 0x2c3e50, fin: 0x1e272e, belly: 0x8395a7 },
      desc: 'A stout ocean battler found around deep pier pilings and drop-offs. Delivers heavy thumping tugs.'
    },
    {
      id: 'flounder',
      name: 'Starry Sand Flounder',
      scientific: 'Platichthys stellatus',
      rarity: 'uncommon',
      sizeCategory: 'Medium',
      habitat: 'ocean_shore',
      timeOfDay: 'night',
      preferredBait: ['worm', 'shrimp'],
      minSize: 32,
      maxSize: 68,
      basePrice: 70,
      fight: { stamina: 24, speed: 0.95, erraticness: 0.35, type: 'sinker' },
      modelType: 'flatfish',
      colors: { body: 0x8d6e63, fin: 0xa1887f, belly: 0xf5f5f5 },
      desc: 'A flat, camouflaged sand-dweller with both eyes curiously positioned on top of its head.'
    },
    {
      id: 'channel_catfish',
      name: 'Channel Bullhead Catfish',
      scientific: 'Ictalurus punctatus',
      rarity: 'uncommon',
      sizeCategory: 'Large',
      habitat: 'freshwater_pond',
      timeOfDay: 'night',
      preferredBait: ['dough', 'grub', 'worm'],
      minSize: 55,
      maxSize: 110,
      basePrice: 95,
      fight: { stamina: 32, speed: 1.0, erraticness: 0.3, type: 'sinker' },
      modelType: 'catfish',
      colors: { body: 0x3d3d3d, fin: 0x222f3e, belly: 0xc8d6e5, whiskers: true },
      desc: 'Night prowler of the pond bed. Senses food using long sensory whiskers and dives deep when hooked.'
    },

    // --- RARE FISH ---
    {
      id: 'mahi_mahi',
      name: 'Bull Dorado (Mahi-Mahi)',
      scientific: 'Coryphaena hippurus',
      rarity: 'rare',
      sizeCategory: 'Large',
      habitat: 'ocean_deep',
      timeOfDay: 'day',
      preferredBait: ['anchovy', 'squid', 'lure'],
      minSize: 90,
      maxSize: 175,
      basePrice: 240,
      fight: { stamina: 42, speed: 1.9, erraticness: 0.75, type: 'dart' },
      modelType: 'dorado',
      colors: { body: 0xffd32a, fin: 0x0be881, belly: 0x05c46b },
      desc: 'Known as the Dolphin Fish, glowing with electric chartreuse and gold. Extremely fast and acrobatic.'
    },
    {
      id: 'swordfish',
      name: 'Gladiator Broadbill Swordfish',
      scientific: 'Xiphias gladius',
      rarity: 'rare',
      sizeCategory: 'Large',
      habitat: 'ocean_deep',
      timeOfDay: 'all',
      preferredBait: ['squid', 'anchovy'],
      minSize: 160,
      maxSize: 310,
      basePrice: 340,
      fight: { stamina: 52, speed: 2.1, erraticness: 0.75, type: 'dart' },
      modelType: 'swordfish',
      colors: { body: 0x1e3799, fin: 0x0c2461, belly: 0xdff9fb, sword: true },
      desc: 'Wields a flat, sword-like bill longer than an arm. Slices through waves at exhilarating speeds.'
    },
    {
      id: 'golden_koi',
      name: 'Emperor Gold Kohaku Koi',
      scientific: 'Cyprinus carpio var.',
      rarity: 'rare',
      sizeCategory: 'Large',
      habitat: 'freshwater_pond',
      timeOfDay: 'all',
      preferredBait: ['dough', 'grub', 'lure'],
      minSize: 60,
      maxSize: 115,
      basePrice: 280,
      fight: { stamina: 38, speed: 1.3, erraticness: 0.45, type: 'cruiser' },
      modelType: 'carp',
      colors: { body: 0xff9f43, fin: 0xff6b6b, belly: 0xffffff },
      desc: 'An exquisite royal ornamental koi with radiant orange-gold scales. Said to bring immense prosperity.'
    },
    {
      id: 'giant_trevally',
      name: 'Giant Trevally (GT)',
      scientific: 'Caranx ignobilis',
      rarity: 'rare',
      sizeCategory: 'Large',
      habitat: 'ocean_deep',
      timeOfDay: 'sunset',
      preferredBait: ['anchovy', 'squid'],
      minSize: 95,
      maxSize: 175,
      basePrice: 310,
      fight: { stamina: 48, speed: 1.8, erraticness: 0.65, type: 'sinker' },
      modelType: 'trevally',
      colors: { body: 0x485460, fin: 0x1e272e, belly: 0xd2dae2 },
      desc: 'The heavyweight brute of island headlands. Strikes surface lures with explosive detonations!'
    },
    {
      id: 'electric_eel',
      name: 'High-Voltage River Eel',
      scientific: 'Electrophorus electricus',
      rarity: 'rare',
      sizeCategory: 'Large',
      habitat: 'freshwater_pond',
      timeOfDay: 'night',
      preferredBait: ['grub', 'shrimp'],
      minSize: 110,
      maxSize: 220,
      basePrice: 290,
      fight: { stamina: 44, speed: 1.6, erraticness: 0.8, type: 'dart' },
      modelType: 'serpent',
      colors: { body: 0x2c3e50, fin: 0xd4ac0d, belly: 0xf1c40f },
      desc: 'A sinuous serpentine creature whose muscular body crackles with bio-electricity, shocking your line!'
    },

    // --- EPIC FISH ---
    {
      id: 'yellowfin_tuna',
      name: 'Yellowfin Titan Tuna',
      scientific: 'Thunnus albacares',
      rarity: 'epic',
      sizeCategory: 'Monster',
      habitat: 'ocean_deep',
      timeOfDay: 'day',
      preferredBait: ['squid', 'anchovy', 'lure'],
      minSize: 150,
      maxSize: 260,
      basePrice: 620,
      fight: { stamina: 68, speed: 2.3, erraticness: 0.8, type: 'cruiser' },
      modelType: 'tuna',
      colors: { body: 0x0c2461, fin: 0xfbc531, belly: 0x487eb0 },
      desc: 'A warm-blooded ocean bullet of solid muscle. Capable of spooling 200 meters of reel line in seconds.'
    },
    {
      id: 'arapaima',
      name: 'Prehistoric Arapaima Gigas',
      scientific: 'Arapaima gigas',
      rarity: 'epic',
      sizeCategory: 'Monster',
      habitat: 'freshwater_pond',
      timeOfDay: 'sunset',
      preferredBait: ['grub', 'anchovy', 'lure'],
      minSize: 180,
      maxSize: 310,
      basePrice: 690,
      fight: { stamina: 72, speed: 1.7, erraticness: 0.85, type: 'sinker' },
      modelType: 'arapaima',
      colors: { body: 0x1b4f72, fin: 0x922b21, belly: 0xe74c3c },
      desc: 'A living fossil with bulletproof armored scales tipped in bloody crimson. Breaches water to gulp air!'
    },
    {
      id: 'great_barracuda',
      name: 'Silver Fang Barracuda',
      scientific: 'Sphyraena barracuda',
      rarity: 'epic',
      sizeCategory: 'Large',
      habitat: 'ocean_deep',
      timeOfDay: 'all',
      preferredBait: ['anchovy', 'squid', 'lure'],
      minSize: 120,
      maxSize: 210,
      basePrice: 560,
      fight: { stamina: 58, speed: 2.4, erraticness: 0.9, type: 'dart' },
      modelType: 'barracuda',
      colors: { body: 0x718093, fin: 0x2f3640, belly: 0xf5f6fa },
      desc: 'Armed with dagger teeth and lightning acceleration. Attacks with explosive ferocious bursts.'
    },
    {
      id: 'bioluminescent_angler',
      name: 'Abyssal Lantern Angler',
      scientific: 'Melanocetus johnsonii',
      rarity: 'epic',
      sizeCategory: 'Medium',
      habitat: 'ocean_deep',
      timeOfDay: 'night',
      preferredBait: ['shrimp', 'squid'],
      minSize: 60,
      maxSize: 120,
      basePrice: 720,
      fight: { stamina: 64, speed: 1.5, erraticness: 0.85, type: 'sinker' },
      modelType: 'angler',
      colors: { body: 0x1e272e, fin: 0x00d2d3, belly: 0x01a3a4, glowingLure: true },
      desc: 'Rising from oceanic trenches, it dangles an ethereal glowing orb to mesmerize prey in the black abyss.'
    },
    {
      id: 'alligator_gar',
      name: 'Gargantuan Alligator Gar',
      scientific: 'Atractosteus spatula',
      rarity: 'epic',
      sizeCategory: 'Monster',
      habitat: 'freshwater_pond',
      timeOfDay: 'all',
      preferredBait: ['anchovy', 'grub', 'lure'],
      minSize: 180,
      maxSize: 320,
      basePrice: 780,
      fight: { stamina: 74, speed: 1.75, erraticness: 0.8, type: 'sinker' },
      modelType: 'gar',
      colors: { body: 0x4b6584, fin: 0x2d3436, belly: 0xa5b1c2 },
      desc: 'Ancient river stalker with an alligator-like double row of razor teeth and interlocking ganoid enamel scales.'
    },

    // --- BIGGER / GIANT / COLOSSAL FISH (USER REQUEST!) ---
    {
      id: 'giant_bluefin',
      name: 'Grand Monarch Bluefin Tuna',
      scientific: 'Thunnus thynnus maximus',
      rarity: 'epic',
      sizeCategory: 'Monster',
      habitat: 'ocean_deep',
      timeOfDay: 'day',
      preferredBait: ['squid', 'anchovy', 'lure'],
      minSize: 240,
      maxSize: 380, // Over 3.8 METERS!
      basePrice: 1100,
      fight: { stamina: 82, speed: 2.5, erraticness: 0.85, type: 'cruiser' },
      modelType: 'tuna',
      colors: { body: 0x0c2461, fin: 0xf1c40f, belly: 0x4bcffa },
      desc: 'Weighing over 500 kilograms, this apex pelagic titan tears through deep open ocean currents like a torpedo.'
    },
    {
      id: 'mekong_catfish',
      name: 'Colossal Mekong River Behemoth',
      scientific: 'Pangasianodon gigas',
      rarity: 'epic',
      sizeCategory: 'Monster',
      habitat: 'freshwater_pond',
      timeOfDay: 'night',
      preferredBait: ['dough', 'grub'],
      minSize: 210,
      maxSize: 350, // 3.5 METERS!
      basePrice: 980,
      fight: { stamina: 80, speed: 1.3, erraticness: 0.6, type: 'sinker' },
      modelType: 'catfish',
      colors: { body: 0x485460, fin: 0x1e272e, belly: 0xd2dae2 },
      desc: 'The undisputed heavyweight monarch of freshwaters. Its colossal girth can exceed 300 kilograms of pure muscle.'
    },
    {
      id: 'giant_sawfish',
      name: 'Primeval Sawfish Titan',
      scientific: 'Pristis pristis',
      rarity: 'epic',
      sizeCategory: 'Monster',
      habitat: 'ocean_deep',
      timeOfDay: 'sunset',
      preferredBait: ['squid', 'anchovy'],
      minSize: 320,
      maxSize: 550, // 5.5 METERS!
      basePrice: 1450,
      fight: { stamina: 88, speed: 2.0, erraticness: 0.9, type: 'sinker' },
      modelType: 'sawfish',
      colors: { body: 0x576574, fin: 0x222f3e, belly: 0xc8d6e5, saw: true },
      desc: 'Armed with a fearsome 1.5-meter toothed rostrum blade that slashes schools of fish in deep coastal trenches.'
    },
    {
      id: 'great_white_shark',
      name: 'Apex Great White Shark',
      scientific: 'Carcharodon carcharias',
      rarity: 'legendary',
      sizeCategory: 'Colossal',
      habitat: 'ocean_deep',
      timeOfDay: 'all',
      preferredBait: ['squid', 'anchovy', 'lure'],
      minSize: 420,
      maxSize: 650, // 6.5 METERS! Over 2 tons!
      basePrice: 2400,
      fight: { stamina: 92, speed: 2.4, erraticness: 0.95, type: 'sinker' },
      modelType: 'shark',
      colors: { body: 0x2f3640, fin: 0x1e272e, belly: 0xf5f6fa },
      desc: 'The undisputed ocean apex predator. Over six meters of raw prehistoric power with rows of serrated razor teeth.'
    },
    {
      id: 'giant_oarfish',
      name: 'King of Herrings (Giant Oarfish)',
      scientific: 'Regalecus glesne',
      rarity: 'legendary',
      sizeCategory: 'Colossal',
      habitat: 'ocean_deep',
      timeOfDay: 'night',
      preferredBait: ['shrimp', 'squid', 'lure'],
      minSize: 550,
      maxSize: 850, // 8.5 METERS!
      basePrice: 2800,
      fight: { stamina: 90, speed: 2.1, erraticness: 1.1, type: 'floater' },
      modelType: 'oarfish',
      colors: { body: 0xdff9fb, fin: 0xff3838, belly: 0xc7ecee, crest: true },
      desc: 'The mythical sea serpent of ancient maritime lore! A ribbon of gleaming silver measuring up to 8.5 meters with a flaming crimson crown.'
    },
    {
      id: 'beluga_sturgeon',
      name: 'Imperial Beluga Sturgeon',
      scientific: 'Huso huso',
      rarity: 'legendary',
      sizeCategory: 'Colossal',
      habitat: 'freshwater_pond',
      timeOfDay: 'all',
      preferredBait: ['dough', 'grub', 'lure'],
      minSize: 380,
      maxSize: 700, // 7.0 METERS!
      basePrice: 3200,
      fight: { stamina: 94, speed: 1.8, erraticness: 0.85, type: 'sinker' },
      modelType: 'sturgeon',
      colors: { body: 0x2d3436, fin: 0x636e72, belly: 0xdfe6e9, scutes: true },
      desc: 'A colossal armored titan surviving from the age of dinosaurs. Can live for over a century and grow past 7 meters.'
    },
    {
      id: 'giant_squid',
      name: 'Colossal Abyssal Kraken Squid',
      scientific: 'Architeuthis dux',
      rarity: 'colossal',
      sizeCategory: 'Titan',
      habitat: 'ocean_deep',
      timeOfDay: 'night',
      preferredBait: ['squid', 'shrimp', 'lure'],
      minSize: 800,
      maxSize: 1300, // 13 METERS!
      basePrice: 4500,
      fight: { stamina: 96, speed: 2.5, erraticness: 1.2, type: 'dart' },
      modelType: 'squid',
      colors: { body: 0xc0392b, fin: 0x8b0000, belly: 0xff7675, tentacles: true },
      desc: 'Rises from midnight abyssal trenches! Possesses dinner-plate eyes and massive clubbed tentacles that dwarf whaling boats.'
    },
    {
      id: 'dunkleosteus',
      name: 'Armored Titan Dunkleosteus',
      scientific: 'Dunkleosteus terrelli',
      rarity: 'colossal',
      sizeCategory: 'Titan',
      habitat: 'ocean_deep',
      timeOfDay: 'night',
      preferredBait: ['squid', 'lure'],
      minSize: 650,
      maxSize: 1000, // 10 METERS!
      basePrice: 5200,
      fight: { stamina: 98, speed: 2.4, erraticness: 1.25, type: 'sinker' },
      modelType: 'armored',
      colors: { body: 0x2c3e50, fin: 0x1a252f, belly: 0x7f8c8d, armorPlate: true },
      desc: 'Primeval Devonian super-predator encased in impenetrable bone plate armor, wielding self-sharpening shear-blade jaws.'
    },
    {
      id: 'megalodon_ancestor',
      name: 'Leviathan Prime (Megalodon Rex)',
      scientific: 'Otodus megalodon rex',
      rarity: 'colossal',
      sizeCategory: 'Titan',
      habitat: 'ocean_deep',
      timeOfDay: 'all',
      preferredBait: ['squid', 'lure'],
      minSize: 900,
      maxSize: 1600, // 16 METERS! The ultimate ocean monster!
      basePrice: 6500,
      fight: { stamina: 100, speed: 2.7, erraticness: 1.3, type: 'sinker' },
      modelType: 'shark',
      colors: { body: 0x17202a, fin: 0x0b1016, belly: 0xecf0f1, colossalMouth: true },
      desc: 'The supreme primeval apex sovereign of ocean history. A 16-meter hyper-carnivore capable of swallowing a boat whole.'
    },

    // --- MYTHICAL LEGENDS ---
    {
      id: 'mythic_axolotl',
      name: 'Radiant Pink Axolotl',
      scientific: 'Ambystoma mexicanum mythica',
      rarity: 'legendary',
      sizeCategory: 'Small',
      habitat: 'freshwater_pond',
      timeOfDay: 'all',
      preferredBait: ['grub', 'lure', 'shrimp'],
      minSize: 35,
      maxSize: 75,
      basePrice: 1500,
      fight: { stamina: 70, speed: 1.9, erraticness: 1.0, type: 'dart' },
      modelType: 'axolotl',
      colors: { body: 0xff9ff3, fin: 0xf368e0, belly: 0xffffff, glowing: true },
      desc: 'The mystical water dragon of the island pond! Possesses wondrous feathery gills and glowing coral eyes.'
    },
    {
      id: 'coelacanth',
      name: 'Ancient Living Fossil Coelacanth',
      scientific: 'Latimeria chalumnae',
      rarity: 'legendary',
      sizeCategory: 'Large',
      habitat: 'ocean_deep',
      timeOfDay: 'night',
      preferredBait: ['squid', 'shrimp', 'lure'],
      minSize: 140,
      maxSize: 220,
      basePrice: 1800,
      fight: { stamina: 78, speed: 1.7, erraticness: 0.9, type: 'sinker' },
      modelType: 'coelacanth',
      colors: { body: 0x1e3799, fin: 0x0c2461, belly: 0x4a69bd, spots: true },
      desc: 'Unchanged for 400 million years. Its prehistoric lobed fins move like legs through the dark depths.'
    },
    {
      id: 'dragon_carp',
      name: 'Sky-Ascending Dragon Carp',
      scientific: 'Cyprinus imperialis draconis',
      rarity: 'legendary',
      sizeCategory: 'Monster',
      habitat: 'freshwater_pond',
      timeOfDay: 'sunset',
      preferredBait: ['lure', 'dough'],
      minSize: 160,
      maxSize: 320,
      basePrice: 2800,
      fight: { stamina: 88, speed: 2.4, erraticness: 1.15, type: 'dart' },
      modelType: 'carp',
      colors: { body: 0xff6b6b, fin: 0xff9f43, belly: 0xfeca57, horns: true, glowing: true },
      desc: 'A sacred carp that has gathered enough mystical pond essence to sprout serpentine whiskers, fiery fins, and golden dragon horns.'
    }
  ],

  // 8 FISHING RODS
  rods: [
    {
      id: 'rod_willow',
      name: 'Willow Twig Rod',
      tier: 1,
      price: 0,
      owned: true,
      maxDistance: 18,
      reelSpeed: 1.0,
      tensionCap: 12,
      luckBonus: 1.0,
      barSizeMultiplier: 1.0,
      color: 0x8d6e63,
      glow: null,
      desc: 'A modest rod fashioned from a flexible island willow branch and simple twine. Honest beginnings.'
    },
    {
      id: 'rod_bamboo',
      name: 'Bamboo Stalker',
      tier: 2,
      price: 120,
      owned: false,
      maxDistance: 24,
      reelSpeed: 1.25,
      tensionCap: 16,
      luckBonus: 1.15,
      barSizeMultiplier: 1.08,
      color: 0x9ccc65,
      glow: null,
      desc: 'Crafted from cured island bamboo cane. Lightweight, bouncy, and delivers noticeably longer casts.'
    },
    {
      id: 'rod_fiberglass',
      name: 'Fiberglass Wave Angler',
      tier: 3,
      price: 350,
      owned: false,
      maxDistance: 30,
      reelSpeed: 1.5,
      tensionCap: 20,
      luckBonus: 1.3,
      barSizeMultiplier: 1.18,
      color: 0x29b6f6,
      glow: null,
      desc: 'High-flex composite rod fitted with steel eyelets and smooth spooling action for saltwater fishing.'
    },
    {
      id: 'rod_carbon',
      name: 'Carbon Precision Pro',
      tier: 4,
      price: 850,
      owned: false,
      maxDistance: 38,
      reelSpeed: 1.85,
      tensionCap: 28,
      luckBonus: 1.5,
      barSizeMultiplier: 1.28,
      color: 0x37474f,
      glow: null,
      desc: 'Aerospace-grade graphite fibers woven for lightning hooksets and great tension resistance.'
    },
    {
      id: 'rod_heavy',
      name: 'Abyssal Deep-Sea Heavy',
      tier: 5,
      price: 1800,
      owned: false,
      maxDistance: 45,
      reelSpeed: 2.2,
      tensionCap: 38,
      luckBonus: 1.85,
      barSizeMultiplier: 1.4,
      color: 0xd84315,
      glow: 0xff5722,
      desc: 'Heavy-duty roller guides and reinforced butt-cap engineered specifically to tackle ocean giants.'
    },
    {
      id: 'rod_golden',
      name: 'Midas Golden Rod',
      tier: 6,
      price: 3600,
      owned: false,
      maxDistance: 50,
      reelSpeed: 2.5,
      tensionCap: 45,
      luckBonus: 2.8,
      barSizeMultiplier: 1.55,
      color: 0xffd700,
      glow: 0xffecb3,
      desc: 'Plated in pure island gold. Exudes an aura that irresistibly entices rare, monster, and colossal fish.'
    },
    {
      id: 'rod_starlight',
      name: 'Starlight Biolume Caster',
      tier: 7,
      price: 6500,
      owned: false,
      maxDistance: 55,
      reelSpeed: 2.9,
      tensionCap: 55,
      luckBonus: 3.5,
      barSizeMultiplier: 1.7,
      color: 0x00e5ff,
      glow: 0x18ffff,
      desc: 'Infused with fallen star fragments and ocean phosphors. Glows brightly in the dark and subdues monsters!'
    },
    {
      id: 'rod_neptune',
      name: "Neptune's Leviathan Trident",
      tier: 8,
      price: 12000,
      owned: false,
      maxDistance: 65,
      reelSpeed: 3.6,
      tensionCap: 75,
      luckBonus: 5.0,
      barSizeMultiplier: 2.0,
      color: 0x76ff03,
      glow: 0x00e676,
      desc: 'The mythical sovereign rod of the deep seven seas. Commands the waters and tames 16-meter titan megalodons.'
    }
  ],

  // 8 BAITS
  baits: [
    {
      id: 'none',
      name: 'Bare Hook',
      price: 0,
      count: Infinity,
      biteSpeed: 1.0,
      luckBonus: 1.0,
      preferredFor: [],
      desc: 'Just an unbaited shiny hook. Better than nothing, but big fish are skeptical.'
    },
    {
      id: 'worm',
      name: 'Garden Earthworm',
      price: 5,
      count: 15,
      biteSpeed: 1.3,
      luckBonus: 1.1,
      preferredFor: ['sardine', 'bluegill', 'common_carp', 'flounder'],
      desc: 'Wiggly and lively. Found easily by foraging or shaking island oak and willow trees.'
    },
    {
      id: 'dough',
      name: 'Sweet Bread Dough',
      price: 8,
      count: 8,
      biteSpeed: 1.4,
      luckBonus: 1.15,
      preferredFor: ['common_carp', 'tilapia', 'golden_koi', 'bluegill', 'beluga_sturgeon', 'dragon_carp'],
      desc: 'Rolled flour infused with fragrant vanilla and honey. Irresistible to freshwater species.'
    },
    {
      id: 'grub',
      name: 'Island Tree Grub',
      price: 14,
      count: 5,
      biteSpeed: 1.5,
      luckBonus: 1.3,
      preferredFor: ['rainbow_trout', 'largemouth_bass', 'electric_eel', 'alligator_gar', 'mythic_axolotl'],
      desc: 'Plump white wood grubs shaken free from island oak and willow trees.'
    },
    {
      id: 'cricket',
      name: 'Field Cricket',
      price: 16,
      count: 0,
      biteSpeed: 1.55,
      luckBonus: 1.35,
      preferredFor: ['rainbow_trout', 'largemouth_bass', 'bluegill'],
      desc: 'High-energy jumper that produces enticing surface vibrations when hitting the water.'
    },
    {
      id: 'anchovy',
      name: 'Fresh Saltwater Anchovy',
      price: 30,
      count: 0,
      biteSpeed: 1.75,
      luckBonus: 1.65,
      preferredFor: ['red_snapper', 'sea_bass', 'mahi_mahi', 'yellowfin_tuna', 'great_barracuda', 'giant_sawfish'],
      desc: 'Oily and fragrant cut fish that drives predatory saltwater gamefish and sharks into a frenzy.'
    },
    {
      id: 'squid',
      name: 'Deep-Sea Squid Bait',
      price: 60,
      count: 0,
      biteSpeed: 2.0,
      luckBonus: 2.2,
      preferredFor: ['swordfish', 'yellowfin_tuna', 'giant_trevally', 'giant_bluefin', 'great_white_shark', 'giant_squid', 'megalodon_ancestor', 'dunkleosteus'],
      desc: 'Tough, resilient oceanic tentacle bait favored by the biggest sea monsters and apex sharks.'
    },
    {
      id: 'shrimp',
      name: 'Bioluminescent Firefly Shrimp',
      price: 110,
      count: 0,
      biteSpeed: 2.3,
      luckBonus: 3.0,
      preferredFor: ['bioluminescent_angler', 'coelacanth', 'giant_oarfish', 'giant_squid', 'mythic_axolotl'],
      desc: 'A glowing phosphorescent shrimp gathered at dusk. Lights up the pitch-black ocean trenches.'
    },
    {
      id: 'lure',
      name: 'Golden Dragonfly Lure',
      price: 450,
      count: 0,
      isReusable: true,
      biteSpeed: 2.2,
      luckBonus: 4.0,
      preferredFor: ['rainbow_trout', 'golden_koi', 'dragon_carp', 'great_white_shark', 'megalodon_ancestor', 'dunkleosteus', 'giant_squid'],
      desc: 'A permanent handcrafted lure of gold and prismatic feathers. Never runs out and tempts colossal titan legends!'
    },
    {
      id: 'blood_chum',
      name: 'Abyssal Blood Chum',
      price: 180,
      count: 0,
      biteSpeed: 2.6,
      luckBonus: 3.8,
      preferredFor: ['great_white_shark', 'giant_sawfish', 'megalodon_ancestor', 'dunkleosteus', 'giant_bluefin'],
      desc: 'A rich mixture of oily fish oils and scent that draws colossal sharks and apex leviathans from miles away!'
    },
    {
      id: 'ambrosia',
      name: 'Sacred Dragon Ambrosia',
      price: 280,
      count: 0,
      biteSpeed: 2.8,
      luckBonus: 4.5,
      preferredFor: ['dragon_carp', 'mythic_axolotl', 'giant_oarfish', 'beluga_sturgeon'],
      desc: 'Rare golden nectar pellets infused with ancient spring lotus blossoms. Irresistible to mythical and dragon species!'
    },
    {
      id: 'crab_meat',
      name: 'Fresh Shore Crab Meat',
      price: 25,
      count: 0,
      biteSpeed: 1.8,
      luckBonus: 2.1,
      preferredFor: ['red_snapper', 'sea_bass', 'swordfish', 'great_barracuda', 'giant_sawfish', 'great_white_shark'],
      desc: 'Sweet, fragrant white crab meat harvested from island beach sand crabs. Irresistible to coastal gamefish and predators!'
    }
  ],

  // 9 WEAPONS & TOOLS: SWORDS, SPEARS, AND AXES
  weapons: [
    // --- SWORDS ---
    {
      id: 'sword_cutlass',
      type: 'sword',
      category: 'swords',
      name: "Pirate's Steel Cutlass",
      tier: 1,
      price: 120,
      owned: false,
      damage: 28,
      speed: 1.4,
      reach: 1.8,
      bonus: 'Fast Swing & Quick Crab Slice',
      color: 0xe0e0e0,
      hiltColor: 0xf1c40f,
      desc: 'A curved high-seas naval cutlass with a brass bell guard. Delivers swift, fluid slashes that effortlessly catch sand crabs!'
    },
    {
      id: 'sword_broadsword',
      type: 'sword',
      category: 'swords',
      name: "Knight's Island Claymore",
      tier: 2,
      price: 380,
      owned: false,
      damage: 55,
      speed: 1.1,
      reach: 2.3,
      bonus: 'Heavy Cleave & Tree Forage',
      color: 0xbdc3c7,
      hiltColor: 0x2c3e50,
      desc: 'A hefty double-edged longsword with crossguard and leather-bound grip. Packs tremendous cutting impact on island resources.'
    },
    {
      id: 'sword_titan',
      type: 'sword',
      category: 'swords',
      name: "Titan Abyssal Slayer",
      tier: 3,
      price: 980,
      owned: false,
      damage: 98,
      speed: 1.25,
      reach: 2.6,
      bonus: 'Glows in Dark & +35% Fish Luck',
      color: 0x00cec9,
      glow: 0x81ecec,
      hiltColor: 0x6c5ce7,
      desc: 'An ancient glowing broadblade forged of starlight metal. Emanates azure runic energy that empowers the bearer across all islands.'
    },

    // --- SPEARS ---
    {
      id: 'spear_bamboo',
      type: 'spear',
      category: 'spears',
      name: "Coastal Bamboo Harpoon",
      tier: 1,
      price: 90,
      owned: false,
      damage: 24,
      speed: 1.5,
      reach: 3.0,
      bonus: 'Long Range & Rapid Thrust',
      color: 0xf5cd79,
      tipColor: 0xdfe6e9,
      desc: 'A light, razor-sharp bamboo spear with a barbed bone tip. Perfect for spearing scurrying beach crabs from a distance!'
    },
    {
      id: 'spear_trident',
      type: 'spear',
      category: 'spears',
      name: "Oceanic Bronze Trident",
      tier: 2,
      price: 340,
      owned: false,
      damage: 52,
      speed: 1.2,
      reach: 3.4,
      bonus: 'Triple-Prong Multi-Catch',
      color: 0xd35400,
      tipColor: 0xf39c12,
      desc: 'A heavy three-pronged ceremonial trident forged of marine bronze. Commands the coastal tides and spears multiple crabs at once.'
    },
    {
      id: 'spear_volcanic',
      type: 'spear',
      category: 'spears',
      name: "Volcanic Magma Lance",
      tier: 3,
      price: 920,
      owned: false,
      damage: 92,
      speed: 1.3,
      reach: 3.8,
      bonus: 'Smoking Embers & Flame Trail',
      color: 0x2d3436,
      glow: 0xff3838,
      tipColor: 0xe74c3c,
      desc: 'Forged in the geothermal volcanic caldera with an obsidian spearhead that leaves trails of crackling orange embers.'
    },

    // --- AXES ---
    {
      id: 'axe_hatchet',
      type: 'axe',
      category: 'axes',
      name: "Lumberjack Foraging Hatchet",
      tier: 1,
      price: 80,
      owned: false,
      damage: 32,
      speed: 1.3,
      reach: 1.6,
      woodcutting: 1.5,
      bonus: 'Chops Trees for +50% Extra Loot',
      color: 0x7f8c8d,
      handleColor: 0x8d6e63,
      desc: 'A sharp, durable woodcutter axe. Striking any island tree shakes free bonus coconuts, apples, and live bait!'
    },
    {
      id: 'axe_bearded',
      type: 'axe',
      category: 'axes',
      name: "Viking Bearded Waraxe",
      tier: 2,
      price: 310,
      owned: false,
      damage: 60,
      speed: 1.05,
      reach: 2.1,
      woodcutting: 2.0,
      bonus: 'Heavy Cleave & Instant Tree Shake',
      color: 0x95a5a6,
      handleColor: 0x5d4037,
      desc: 'A broad curved Nordic battleaxe with extended cutting edge. Fells tough timber and cleaves beach shells effortlessly.'
    },
    {
      id: 'axe_colossal',
      type: 'axe',
      category: 'axes',
      name: "Colossal Titan Double-Bit Axe",
      tier: 3,
      price: 950,
      owned: false,
      damage: 105,
      speed: 1.15,
      reach: 2.5,
      woodcutting: 3.0,
      bonus: 'Double Blade & +100% Tree Drops',
      color: 0x2c3e50,
      glow: 0xf1c40f,
      handleColor: 0x1e272e,
      desc: 'A massive double-bladed titan waraxe with gilded runes. One mighty swing rattles ancient trees and sends showers of gold coins tumbling!'
    }
  ],

  // ISLAND UNLOCKS & SEA CHARTERS
  islands: [
    {
      id: 'island_coral',
      name: 'Tropical Coral Atoll',
      price: 200,
      unlocked: false,
      desc: 'A vibrant sun-drenched coral lagoon island with white beaches and turquoise shallows teeming with exotic reef species.',
      badge: 'Coral Reefs & Palms',
      fastTravelPos: { x: 155, y: 3.5, z: -20 }
    },
    {
      id: 'island_volcano',
      name: 'Volcanic Pine Crags',
      price: 500,
      unlocked: false,
      desc: 'Dark volcanic slate cliffs with hot spring ponds and high alpine pines where prehistoric river monsters roam.',
      badge: 'Volcanic Geysers',
      fastTravelPos: { x: -140, y: 8.5, z: -60 }
    },
    {
      id: 'island_titan',
      name: 'Titan Leviathan Atoll',
      price: 1200,
      unlocked: false,
      desc: 'A treacherous deep-sea oceanic trench surrounded by midnight waters where giant sharks, oarfish, and Megalodons dwell.',
      badge: 'Colossal Titans',
      fastTravelPos: { x: 0, y: 4.2, z: 215 }
    }
  ],

  // TREE TYPES & FORAGING LOOT
  trees: {
    palm: {
      name: 'Coconut Palm',
      height: [6, 9],
      drops: [
        { type: 'item', id: 'coconut', name: 'Fresh Coconut', value: 20, chance: 0.5, desc: 'Sweet island fruit! Sell for 20g' },
        { type: 'bait', id: 'grub', count: 2, chance: 0.35 },
        { type: 'gold', amount: 15, chance: 0.25 }
      ]
    },
    oak: {
      name: 'Grand Meadow Oak',
      height: [5, 8],
      drops: [
        { type: 'bait', id: 'worm', count: 4, chance: 0.5 },
        { type: 'bait', id: 'grub', count: 3, chance: 0.4 },
        { type: 'item', id: 'apple', name: 'Sweet Apple', value: 15, chance: 0.35, desc: 'Crisp red apple! Sell for 15g' },
        { type: 'gold', amount: 20, chance: 0.2 }
      ]
    },
    pine: {
      name: 'Mountain Pine',
      height: [7, 11],
      drops: [
        { type: 'bait', id: 'cricket', count: 4, chance: 0.45 },
        { type: 'item', id: 'amber', name: 'Pine Amber Resin', value: 45, chance: 0.25, desc: 'Fossilized amber! Sell for 45g' },
        { type: 'bait', id: 'grub', count: 2, chance: 0.3 },
        { type: 'gold', amount: 25, chance: 0.2 }
      ]
    },
    willow: {
      name: 'Weeping Pond Willow',
      height: [5, 7.5],
      drops: [
        { type: 'bait', id: 'worm', count: 5, chance: 0.5 },
        { type: 'bait', id: 'shrimp', count: 2, chance: 0.3 },
        { type: 'item', id: 'water_lily', name: 'Enchanted Lily Flower', value: 35, chance: 0.3, desc: 'Fragrant flower! Sell for 35g' },
        { type: 'gold', amount: 30, chance: 0.2 }
      ]
    },
    cherry: {
      name: 'Sacred Blossom Tree',
      height: [6, 8.5],
      drops: [
        { type: 'gold', amount: 75, chance: 0.5 },
        { type: 'bait', id: 'shrimp', count: 3, chance: 0.4 },
        { type: 'item', id: 'blossom_gem', name: 'Sakura Star Gem', value: 120, chance: 0.35, desc: 'Rare mystical jewel! Sell for 120g' }
      ]
    }
  }
};
